version: "3.9"

services:
  # Configuração para o Proxy Pub/Sub
  proxy:
    build: ./proxy
    image: prosd/proxy-pubsub
    container_name: prosd-proxy
    environment:  # ⬅️ Este deve estar alinhado com 'build' e 'image'
      - PYTHONUNBUFFERED=1
    ports:
      # XSUB: Entrada para Publishers (Bot)
      - "5557:5557"
      # XPUB: Saída para Subscribers (Cliente, Monitor)
      - "5558:5558"
    command: ["python", "proxy-pub.py"]
    networks:
      - prosd_network

  broker:
    build: ./broker
    image: prosd/broker
    container_name: prosd-broker
    ports:
      - "5555:5555" # Porta Req/Rep
    depends_on:
      - proxy
    networks: # Apenas referenciando a rede
      - prosd_network

  server:
    build: ./server
    environment:
      - SERVER_NAME=Server1
    volumes:
      - ./server/data:/app/data
    depends_on:
      - broker
      - proxy
    restart: unless-stopped
    networks: # Apenas referenciando a rede
      - prosd_network

  bot:
    build: ./bot
    container_name: bot_go
    depends_on:
      - broker
      - proxy
    restart: unless-stopped
    networks: # Apenas referenciando a rede
      - prosd_network

  client_cli:
    build: ./client
    stdin_open: true
    tty: true
    depends_on:
      - broker
      - proxy
    restart: unless-stopped
    networks: # Apenas referenciando a rede
      - prosd_network

  monitor:
    build: ./monitor
    container_name: monitor
    ports:
      - "5000:5000"
    depends_on:
      - proxy
    restart: unless-stopped
    networks: # Apenas referenciando a rede
      - prosd_network

# --- SEÇÃO GLOBAL DE DEFINIÇÃO DE REDES (Onde o driver é especificado) ---
networks:
  prosd_network:
    driver: bridge # O Docker cria uma rede chamada prosd_network